package:
  name: imputed-data-dynamic-threshold
  version: 1.2.0
source:
  url: "https://github.com/lightning-auriga/imputed-data-dynamic-threshold/archive/refs/tags/1.2.0.tar.gz"
  sha256: "e8cf58b1ce2d63703f6ec812a9eaf339560bed2be78fc372ca4eb0000c639574"

build:
  number: '1'
  run_exports:
    - {{ pin_subpackage('imputed-data-dynamic-threshold', max_pin="x") }}

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - {{ compiler('cxx') }}
    - make >=4.2
  host:
    - boost >=1.79
    - zlib
    - htslib
    - gtest
  run:
    - boost
about:
  dev_url: https://github.com/lightning-auriga/imputed-data-dynamic-threshold
  home: https://gitlab.com/lightning-auriga/imputed-data-dynamic-threshold
  license: MIT
  license_file: LICENSE
  summary: compute r2 threshold using Yun Li cleaning method
