{% set version="0.1.4" %}


package:
  name: uncertainty-calibration
  version: {{ version }}

source:
  url: "https://files.pythonhosted.org/packages/28/7a/a9b8f063fca2b3d339bd10d38363d58983e8c79095b81c4c87f3a124e211/uncertainty-calibration-0.1.4.tar.gz"
  sha256: "e99baf2f2ced29b852eb47c25852e4bcc3fff183befef6c35cc239165c6e2634"

build:
  number: 0
  skip: true  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - scikit-learn
    - parameterized
