package:
  name: interpolate-genetic-position
  version: 1.1.0
source:
  url: "https://github.com/lightning-auriga/interpolate-genetic-position/archive/refs/tags/1.1.0.tar.gz"
  sha256: "97aff3bd5790460e46a0633dbf0d0bff8b0bda2569bde63fa367899bb69924d3"

build:
  number: '1'
  run_exports:
    - {{ pin_subpackage('interpolate-genetic-position', max_pin="x") }}

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - {{ compiler('cxx') }}
    - make >=4.2
  host:
    - boost >=1.79
    - zlib
    - libbigwig
    - gmp
    - gtest
    - gmock
    - htslib
  run:
    - boost
about:
  dev_url: https://github.com/lightning-auriga/interpolate-genetic-position
  home: https://gitlab.com/lightning-auriga/interpolate-genetic-position
  license: MIT
  license_file: COPYING
  summary: Use reference genetic map to interpolate genetic position for a query set of variants
